cargo-features = ["profile-rustflags"]

[workspace]
resolver = "2"

members = [
	"hyu",
	"wlm",
]

[workspace.dependencies]
serde = { version = "1.0.197", features = ["derive"] }

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
rustflags = ["-C", "target-cpu=native"]
